### PR TITLE
hocr-wordfreq: word frequency counter

### PR DESCRIPTION
**Pull request by kba**
Python solution for [calculating word frequency](https://github.com/tmbdev/hocr-tools/wiki/Calculate-word-frequency)

### CODE REVIEW

**Comment by stweil** [comment]
Thank you. This small helper could be extended to accept any number of hOCR files.

**Comment by zuphilip** [comment]
Thank you very much @kba!

**Comment by zuphilip** [comment]
@stweil For several hocr files you can also just use two commands, i.e. something like:
```bash
hocr-combine *.html | hocr-wordfreq 
```

**Comment by stweil** [comment]
> This small helper could be extended to accept any number of hOCR files.

... or to get its input from `STDIN`. Then pipes like the one suggested above could be used.

**Pull request merged**
