### PR TITLE
WIP: Reformat hocr-* code according to PEP8

### PR DESCRIPTION
**Pull request by zuphilip**
I just used yapf -i hocr-* with [yapf](https://github.com/google/yapf) version 0.16.3.

### CODE REVIEW

**Comment by zuphilip** [comment]
Travis result for yapf branch: [](https://travis-ci.org/UB-Mannheim/hocr-tools/branches)

**Comment by zuphilip** [comment]
This addresses #15. But we should look in details about the suggested changes and possibly deactivate some rules or not taking all changes. For example, sometimes the arguments of a function are taken on a separate lines (I guess to avoid violating the maximum line length), but these changes looks at least for me a little unfamiliar.

**Comment by stweil** [comment]
I added more changes suggested by `pep8` to a [new branch](https://github.com/tmbdev/hocr-tools/tree/pep8). Should we make such changes for all files, too?

**Comment by zuphilip** [comment]
Wow, that was a fast discussion ;-)

The fixes in your branch looks fine for me. Did you check also the `setup.py` file?

> Should we make such changes for all files, too?

What exactly do you mean?

**Comment by zuphilip** [comment]
BTW should we maybe accept also #108 before the final code reformatting?

**Comment by stweil** [comment]
I checked all Python files with `pep8`, but currently only fixed the first ones in the new branch.

**Pull request merged**
