### PR TITLE
hocr-wordfreq: Allow input from stdin

### PR DESCRIPTION
**Pull request by stweil**
This enables pipes like

    hocr-combine *.html | hocr-wordfreq

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
I added both the line breaks and the spaces intentionally. [PEP-8](https://www.python.org/dev/peps/pep-0008/) suggests a limit of 79 characters per line. It also recommends surrounding certain operators with a single space.

**Comment by zuphilip** [comment]
https://www.python.org/dev/peps/pep-0008/#other-recommendations : 

> Don't use spaces around the = sign when used to indicate a keyword argument or a default parameter value.

**Comment by stweil** [comment]
Good catch. It looks like PEP-8 is more complex than I thought. I updated the commit with removed spaces.

**Comment by zuphilip** [comment]
Thank you very much!

**Pull request merged**
